In [16]:
import torch
import torch.nn as nn

from torchvision.models import resnet18

In [2]:
loss = nn.CrossEntropyLoss()

In [5]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)

In [4]:
print(input)

tensor([[ 1.3457,  0.9627,  0.1693,  0.2497, -1.0094],
        [ 0.5631, -0.8087,  0.0745, -0.3962, -1.1940],
        [-0.2852, -0.1100, -0.6336, -0.3820,  2.9571]], requires_grad=True)


In [6]:
print(target)

tensor([0, 3, 1])


## Testing Through ResNet18

In [35]:
x = torch.randn(1, 3, 224, 224)
y = torch.empty(1, dtype=torch.long).random_(9)

In [36]:
model = resnet18(pretrained=False)
model.fc = nn.Linear(model.fc.in_features, 9)

In [37]:
y_hat = model(x)

In [41]:
y_hat

tensor([[ 0.0378, -0.1334, -0.2855,  0.0388, -0.8222, -0.4199, -0.0096,  1.0483,
          0.3617]], grad_fn=<AddmmBackward0>)

In [42]:
y

tensor([2])

In [40]:
loss(y_hat, y)

tensor(2.5961, grad_fn=<NllLossBackward0>)